2023-03-07 13:04:12,020:__main__:WARNING:ПРЕДУПРЕЖДЕНИЕ: у операции №5 техпроцесса ("ПКЛ-7503-33 ТП ЭЦП", "TP_MO") не найдена норма Тпар из-за отсутствия оборудования или кода профессии. Норма будет взята за 0
2023-03-07 13:08:12,602:__main__:WARNING:ПРЕДУПРЕЖДЕНИЕ: у операции №5 техпроцесса ("ПКЛ-7503-33 ТП ЭЦП", "TP_MO") не найдена норма Тпар из-за отсутствия оборудования или кода профессии. Норма будет взята за 0
2023-03-07 13:09:46,982:__main__:WARNING:ПРЕДУПРЕЖДЕНИЕ: у операции №5 техпроцесса ("ПКЛ-7503-33 ТП ЭЦП", "TP_MO") не найдена норма Тпар из-за отсутствия оборудования или кода профессии. Норма будет взята за 0
2023-03-07 13:09:46,982:__main__:WARNING:<class 'str'>
2023-03-07 13:15:54,729:app:ERROR:Exception on /table_log/Test_2 [GET]
Traceback (most recent call last):
  File "C:\Users\Dunajkin-D-M.ZVEZDA\.virtualenvs\server-eSlfTvgE\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Dunajkin-D-M.ZVEZDA\.virtualenvs\server-eSlfTvgE\lib\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Dunajkin-D-M.ZVEZDA\.virtualenvs\server-eSlfTvgE\lib\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Dunajkin-D-M.ZVEZDA\.virtualenvs\server-eSlfTvgE\lib\site-packages\flask\app.py", line 2156, in make_response
    rv = self.json.response(rv)
  File "C:\Users\Dunajkin-D-M.ZVEZDA\.virtualenvs\server-eSlfTvgE\lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "C:\Users\Dunajkin-D-M.ZVEZDA\.virtualenvs\server-eSlfTvgE\lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "c:\users\dunajkin-d-m.zvezda\appdata\local\programs\python\python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\dunajkin-d-m.zvezda\appdata\local\programs\python\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\dunajkin-d-m.zvezda\appdata\local\programs\python\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Dunajkin-D-M.ZVEZDA\.virtualenvs\server-eSlfTvgE\lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Response is not JSON serializable
2023-03-07 13:16:25,129:app:ERROR:Exception on /table_log/Test_2 [GET]
Traceback (most recent call last):
  File "C:\Users\Dunajkin-D-M.ZVEZDA\.virtualenvs\server-eSlfTvgE\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Dunajkin-D-M.ZVEZDA\.virtualenvs\server-eSlfTvgE\lib\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Dunajkin-D-M.ZVEZDA\.virtualenvs\server-eSlfTvgE\lib\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Dunajkin-D-M.ZVEZDA\.virtualenvs\server-eSlfTvgE\lib\site-packages\flask\app.py", line 2156, in make_response
    rv = self.json.response(rv)
  File "C:\Users\Dunajkin-D-M.ZVEZDA\.virtualenvs\server-eSlfTvgE\lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "C:\Users\Dunajkin-D-M.ZVEZDA\.virtualenvs\server-eSlfTvgE\lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "c:\users\dunajkin-d-m.zvezda\appdata\local\programs\python\python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\dunajkin-d-m.zvezda\appdata\local\programs\python\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\dunajkin-d-m.zvezda\appdata\local\programs\python\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Dunajkin-D-M.ZVEZDA\.virtualenvs\server-eSlfTvgE\lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Response is not JSON serializable
2023-03-07 13:17:21,328:__main__:WARNING: Table read action falled with errors: Object of type Row is not JSON serializable
2023-03-17 08:28:06,527:__main__:WARNING: Login action falled with errors: No user with this password
2023-03-17 08:33:24,935:__main__:WARNING: Login action falled with errors: No user with this password
2023-03-17 08:34:00,002:__main__:WARNING: Login action falled with errors: No user with this password
2023-03-17 08:41:45,934:__main__:WARNING: Login action falled with errors: No user with this password
2023-03-17 08:45:39,825:__main__:WARNING: Login action falled with errors: No user with this password
2023-03-17 08:49:54,334:__main__:WARNING: Login action falled with errors: No user with this password
2023-03-17 08:52:25,720:__main__:WARNING: Login action falled with errors: No user with this password
2023-03-17 08:53:10,296:__main__:WARNING: Login action falled with errors: No user with this password
2023-03-17 08:55:04,154:__main__:WARNING: Login action falled with errors: No user with this password
2023-03-17 08:56:15,110:__main__:WARNING: Login action falled with errors: No user with this password
2023-03-17 08:57:22,775:__main__:WARNING: Login action falled with errors: No user with this password
2023-03-17 08:58:40,566:__main__:WARNING: Login action falled with errors: No user with this password
